### PR TITLE
API_KEY support + X-Parse headers support

### PR DESCRIPTION
**Pull request by jakubknejzlik**
Hi I've found this node module and decided to add support for API_KEY authorization. For support the "old way" _options property is created (to hold various information – could be useful for future updates). Don't hasitate to contact me if this need some changes.

### CODE REVIEW

**Comment by mikehua** [comment]
Agreed.  @Leveton can you merge this into master?
Thanks

**Comment by Leveton** [comment]
@jakubknejzlik did you test all the functionality?  It looks like you changed the whole Parse.js file.

**Comment by jakubknejzlik** [comment]
Well, I did, but it's just few lines of code (the merge of my commit just looks weird that everything has changed, but if you check, it's just about the constructor and request functions)

**Comment by jakubknejzlik** [comment]
I'm sorry for closing, just clicked the wrong button :)

**Comment by Leveton** [comment]
Merged, thanks.

**Pull request closed without merging**
