### PR TITLE
Handle Parse Service Errors

### PR DESCRIPTION
**Pull request by gasi**
Pass Parse error messages and codes to client. This builds upon #16.

### CODE REVIEW

**Comment by gasi** [comment]
Any update on this?

**Comment by Leveton** [comment]
This is merged, thanks.

**Comment by aseemk** [comment]
Hi folks,

It doesn't look like this actually merged: https://github.com/Leveton/node-parse-api/compare/master...FiftyThree:capture-service-errors still shows a diff.

However, I think @gasi's change (for the better in most cases) introduced one regression: if Parse returns an *HTML* error response (instead of a JSON one), this lib now returns a JSON parsing error:

```
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/app/models/node_modules/node-parse-api/lib/Parse.js:327:44)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)
```

When it previously used to report back a slightly more helpful e.g. `HTTP error 503`.

—

I've written some code that parses (no pun intended :smile:) our database's errors in a way that achieves both of these things ([link](https://github.com/thingdom/node-neo4j/blob/ed5a6bb58fa3d6fee2dd0f9959c08397558e501f/lib-new/errors.coffee#L10-L39)), e.g.:

```
// if proper JSON error, error stack trace looks like this:
neo4j.ClientError: [Statement.EntityNotFound] Node with id 741073

// otherwise, if an HTML error (e.g. from HAProxy):
neo4j.DatabaseError: 503 Service Unavailable response for POST /db/data/transaction/commit: "<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"
```

Happy to fix/improve this here, if you're still interested in accepting this PR. Let me know. Thanks!

**Comment by Leveton** [comment]
@aseemk yes, send another PR, thanks.

**Comment by gasi** [comment]
@Leveton Under what license is this library available? I couldn’t find it in README nor in `package.json` and even the original fork (https://github.com/tenorviol/node-parse-api) has no license.

**Comment by Leveton** [comment]
@gasi good catch.  Let's do MIT.

**Comment by gasi** [comment]
Can’t get the tests to pass on `master`, so I decided to solve the issue at an app level.

**Pull request closed without merging**
